CLRI   ;Clear Inhibit
SETZ   ;Initialize Crate
;--------------------------Commands for BARC CM88----------------------------
DATA = 12    ;Singles no individual gates
NAF : 13 0 16
DATA = 50
NAF : 13 0 17        ;Set LLD(mV)=2*number
DATA = 254
NAF : 13 1 17        ;Set ULD (0-255) to maximum
;--------------------------Commands for BARC CM88----------------------------
DATA = 9     ;Coin. no individual gates
NAF : 18 0 16
DATA = 50
NAF : 18 0 17        ;Set LLD(mV)=2*number
DATA = 254
NAF : 18 1 17        ;Set ULD (0-255) to maximum
NAF : 18 12 26         ;Enable LAM
;---------------------------------------------------------------------------
CLRC                  ;For first LAM
END
;---------------------------------------------------------------------------
;The folowing keywords are used in these files:
;SETZ (Camac Z), CLRC (Camac C), SETI (Set Inhibit), CLRI (Clear Inhibit),
;DATA = <decimal number>, NAF : <N> <A> <F> (Camac NAF command)
;DLY = <decimal number=Delay in milliseconds>
;The END at the end is not compulsory
;Comments can be put after a semicolon
;---------------------------------------------------------------------------
