CLRI   ;Clear Inhibit
SETZ   ;Initialize Crate
DATA = 50
NAF : 11 0 17        ;Set LLD of Ch0
DATA = 50
NAF : 11 1 17        ;Set LLD of Ch1
DATA = 50
NAF : 11 2 17        ;Set LLD of Ch2
DATA = 50
NAF : 11 3 17        ;Set LLD of Ch3
;--------------------------Commands for BARC CM88----------------------------
DATA = 9     ;Coin. no individual gates
NAF : 18 0 16
DATA = 50
NAF : 18 0 17        ;Set LLD(mV)=2*number
DATA = 254
NAF : 18 1 17        ;Set ULD (0-255) to maximum
NAF : 18 12 26         ;Enable LAM
;---------------------------------------------------------------------------
CLRC                  ;For first LAM
END
;---------------------------------------------------------------------------
;The folowing keywords are used in these files:
;SETZ (Camac Z), CLRC (Camac C), SETI (Set Inhibit), CLRI (Clear Inhibit),
;DATA = <decimal number>, NAF : <N> <A> <F> (Camac NAF command)
;DLY = <decimal number=Delay in milliseconds>
;The END at the end is not compulsory
;Comments can be put after a semicolon
;---------------------------------------------------------------------------
