CLRI   ;Clear Inhibit
SETZ   ;Initialize Crate
;---------------------------------------------------------------------------
END
;---------------------------------------------------------------------------
;The folowing keywords are used in these files:
;SETZ (Camac Z), CLRC (Camac C), SETI (Set Inhibit), CLRI (Clear Inhibit),
;DATA = <decimal number>, NAF : <N> <A> <F> (Camac NAF command)
;DLY = <decimal number=Delay in milliseconds>
;The END at the end is not compulsory
;Comments can be put after a semicolon
;---------------------------------------------------------------------------
