CLRI   ;Clear Inhibit
SETZ   ;Initialize Crate
SETI
;--------------------------Commands for AD413--------------------------------
NAF : 6 0 9         ;Clear the ADC
DATA = 41728         ;41728 for Coinc mode Lam disabled
NAF : 6 0 16        ;Control Register 1
DATA = 0             ;All gates enabled
NAF : 6 1 16        ;Control Register 2
DATA = 50
NAF : 6 0 17        ;Set LLD of Ch0 (Default is 36*2=72mV)
DATA = 50
NAF : 6 1 17        ;Set LLD of Ch1 (Default is 36*2=72mV)
DATA = 50
NAF : 6 2 17        ;Set LLD of Ch2 (Default is 36*2=72mV)
DATA = 50
NAF : 6 3 17        ;Set LLD of Ch3 (Default is 36*2=72mV)
;--------------------------Commands for AD413--------------------------------
NAF : 10 0 9         ;Clear the ADC
DATA = 62208         ;62208 for Singles Mode,Lam enabled
NAF : 10 0 16        ;Control Register 1
DATA = 16            ;B5=1 to disable master gate
NAF : 10 1 16        ;Control Register 2
DATA = 50
NAF : 10 0 17        ;Set LLD of Ch0 (Default is 36*2=72mV)
DATA = 50
NAF : 10 1 17        ;Set LLD of Ch1 (Default is 36*2=72mV)
DATA = 50
NAF : 10 2 17        ;Set LLD of Ch2 (Default is 36*2=72mV)
DATA = 50
NAF : 10 3 17        ;Set LLD of Ch3 (Default is 36*2=72mV)
;---------------------------------------------------------------------------
CLRI
;--------------------------Commands for BARC CM88----------------------------
DATA = 9     ;Coin. no individual gates
NAF : 13 0 16
DATA = 50
NAF : 13 0 17        ;Set LLD(mV)=2*number
DATA = 254
NAF : 13 1 17        ;Set ULD (0-255) to maximum
NAF : 13 12 26         ;Enable LAM
;--------------------------Commands for BARC CM88----------------------------
DATA = 12    ;Singles no individual gates
NAF : 18 0 16
DATA = 50
NAF : 18 0 17        ;Set LLD(mV)=2*number
DATA = 254
NAF : 18 1 17        ;Set ULD (0-255) to maximum
;---------------------------------------------------------------------------
CLRC                  ;For first LAM
END
;---------------------------------------------------------------------------
;The folowing keywords are used in these files:
;SETZ (Camac Z), CLRC (Camac C), SETI (Set Inhibit), CLRI (Clear Inhibit),
;DATA = <decimal number>, NAF : <N> <A> <F> (Camac NAF command)
;DLY = <decimal number=Delay in milliseconds>
;The END at the end is not compulsory
;Comments can be put after a semicolon
;---------------------------------------------------------------------------
